### PR TITLE
fixes: 500 internal server error on compare page

### PR DESCRIPTION
**Pull request by dhairyathedev**
Fixes:
> There is one issue with the suggestions fetching.
Screenshot 2024-06-29 at 5 20 46 PM

_Originally posted by @dhairyathedev in https://github.com/ashutosh-rath02/git-re/issues/329#issuecomment-2198123977_

### CODE REVIEW

**Comment by dhairyathedev** [comment]
Merge this PR @Swastik19Nit

**Comment by dhairyathedev** [comment]
### Change Log
- Formatted the code
- Change `fetchAllLeaderboardData()` function

**Comment by Swastik19Nit** [comment]
In this code , wont it show suggestions only from the first page of leaderboard if page always is set to 1?

**Comment by Swastik19Nit** [comment]
@dhairyathedev

**Comment by dhairyathedev** [comment]
> In this code , wont it show suggestions only from the first page of leaderboard if page always is set to 1?

Yeah, good catch. So, need to reconfigure the fetching of the data. Shooting up a new PR shortly.

**Pull request merged**
